// timetable.js
// Key used in localStorage
const STORAGE_KEY = "futa_timetable_v1";

// Helper: get data from localStorage (or default)
function loadTimetable() {
  const raw = localStorage.getItem(STORAGE_KEY);
    if (!raw) return { monday: [], tuesday: [], wednesday: [], thursday: [], friday: [] };
      try {
          return JSON.parse(raw);
            } catch (e) {
                console.error("Failed to parse timetable:", e);
                    return { monday: [], tuesday: [], wednesday: [], thursday: [], friday: [] };
                      }
                      }

                      // Helper: save data to localStorage
                      function saveTimetable(data) {
                        localStorage.setItem(STORAGE_KEY, JSON.stringify(data));
                        }

                        // Render the whole timetable to the page
                        function renderTimetable() {
                          const data = loadTimetable();
                            // get all day columns
                              const dayColumns = document.querySelectorAll(".day-column");
                                dayColumns.forEach(col => {
                                    const day = col.getAttribute("data-day");
                                        const slot = col.querySelector(".day-slot");
                                            slot.innerHTML = ""; // clear
                                                // sort classes by start time for nicer order
                                                    const list = data[day] || [];
                                                        list.sort((a,b) => a.startTime.localeCompare(b.startTime));
                                                            list.forEach(item => {
                                                                  const courseEl = document.createElement("div");
                                                                        courseEl.className = "course";
                                                                              courseEl.innerHTML = `
                                                                                      <p class="course-code">${escapeHtml(item.courseCode)}</p>
                                                                                              <p class="course-time">${formatTime(item.startTime)} - ${formatTime(item.endTime)}</p>
                                                                                                      <p class="course-venue">${escapeHtml(item.venue)}</p>
                                                                                                              <div class="small-btns">
                                                                                                                        <button class="del-btn" data-id="${item.id}" title="Delete">✖</button>
                                                                                                                                </div>
                                                                                                                                      `;
                                                                                                                                            slot.appendChild(courseEl);
                                                                                                                                                });
                                                                                                                                                  });

                                                                                                                                                    // attach delete listeners
                                                                                                                                                      document.querySelectorAll(".del-btn").forEach(btn => {
                                                                                                                                                          btn.addEventListener("click", (e) => {
                                                                                                                                                                const id = e.currentTarget.getAttribute("data-id");
                                                                                                                                                                      deleteClassById(id);
                                                                                                                                                                          });
                                                                                                                                                                            });
                                                                                                                                                                            }

                                                                                                                                                                            // Create unique id
                                                                                                                                                                            function makeId() {
                                                                                                                                                                              return Date.now().toString(36) + Math.random().toString(36).slice(2,6);
                                                                                                                                                                              }

                                                                                                                                                                              // Delete a class by id (search all days)
                                                                                                                                                                              function deleteClassById(id) {
                                                                                                                                                                                const data = loadTimetable();
                                                                                                                                                                                  let changed = false;
                                                                                                                                                                                    for (const day of Object.keys(data)) {
                                                                                                                                                                                        const before = data[day].length;
                                                                                                                                                                                            data[day] = data[day].filter(item => item.id !== id);
                                                                                                                                                                                                if (data[day].length !== before) changed = true;
                                                                                                                                                                                                  }
                                                                                                                                                                                                    if (changed) {
                                                                                                                                                                                                        saveTimetable(data);
                                                                                                                                                                                                            renderTimetable();
                                                                                                                                                                                                              }
                                                                                                                                                                                                              }

                                                                                                                                                                                                              // Basic time formatting (HH:MM -> 8:00 AM)
                                                                                                                                                                                                              function formatTime(hhmm) {
                                                                                                                                                                                                                if (!hhmm) return "";
                                                                                                                                                                                                                  const [hStr, mStr] = hhmm.split(":");
                                                                                                                                                                                                                    let h = parseInt(hStr,10);
                                                                                                                                                                                                                      const m = mStr || "00";
                                                                                                                                                                                                                        const am = h < 12 ? "AM" : "PM";
                                                                                                                                                                                                                          if (h === 0) h = 12;
                                                                                                                                                                                                                            if (h > 12) h = h - 12;
                                                                                                                                                                                                                              return `${h}:${m} ${am}`;
                                                                                                                                                                                                                              }

                                                                                                                                                                                                                              // escapeHtml to avoid injection
                                                                                                                                                                                                                              function escapeHtml(str) {
                                                                                                                                                                                                                                if (!str) return "";
                                                                                                                                                                                                                                  return str.replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;");
                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                  // Form handling
                                                                                                                                                                                                                                  document.addEventListener("DOMContentLoaded", () => {
                                                                                                                                                                                                                                    const form = document.getElementById("add-class-form");
                                                                                                                                                                                                                                      const msg = document.getElementById("form-msg");
                                                                                                                                                                                                                                        const clearBtn = document.getElementById("clear-btn");

                                                                                                                                                                                                                                          // initial render
                                                                                                                                                                                                                                            renderTimetable();

                                                                                                                                                                                                                                              // Submit handler
                                                                                                                                                                                                                                                form.addEventListener("submit", (ev) => {
                                                                                                                                                                                                                                                    ev.preventDefault();
                                                                                                                                                                                                                                                        msg.textContent = "";

                                                                                                                                                                                                                                                            const courseCode = form.courseCode.value.trim();
                                                                                                                                                                                                                                                                const day = form.day.value;
                                                                                                                                                                                                                                                                    const startTime = form.startTime.value;
                                                                                                                                                                                                                                                                        const endTime = form.endTime.value;
                                                                                                                                                                                                                                                                            const venue = form.venue.value.trim();

                                                                                                                                                                                                                                                                                // Basic validation
                                                                                                                                                                                                                                                                                    if (!courseCode || !day || !startTime || !endTime || !venue) {
                                                                                                                                                                                                                                                                                          msg.style.color = "red";
                                                                                                                                                                                                                                                                                                msg.textContent = "Please fill all fields.";
                                                                                                                                                                                                                                                                                                      return;
                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                              if (startTime >= endTime) {
                                                                                                                                                                                                                                                                                                                    msg.style.color = "red";
                                                                                                                                                                                                                                                                                                                          msg.textContent = "Start time must be before end time.";
                                                                                                                                                                                                                                                                                                                                return;
                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                        // Build class object
                                                                                                                                                                                                                                                                                                                                            const newClass = {
                                                                                                                                                                                                                                                                                                                                                  id: makeId(),
                                                                                                                                                                                                                                                                                                                                                        courseCode,
                                                                                                                                                                                                                                                                                                                                                              day,
                                                                                                                                                                                                                                                                                                                                                                    startTime,   // saved in 24h "HH:MM" for easy sorting
                                                                                                                                                                                                                                                                                                                                                                          endTime,
                                                                                                                                                                                                                                                                                                                                                                                venue
                                                                                                                                                                                                                                                                                                                                                                                    };

                                                                                                                                                                                                                                                                                                                                                                                        // Save to storage
                                                                                                                                                                                                                                                                                                                                                                                            const data = loadTimetable();
                                                                                                                                                                                                                                                                                                                                                                                                data[day].push(newClass);
                                                                                                                                                                                                                                                                                                                                                                                                    saveTimetable(data);

                                                                                                                                                                                                                                                                                                                                                                                                        // Feedback + reset (keep in case user wants to add more quickly)
                                                                                                                                                                                                                                                                                                                                                                                                            msg.style.color = "#006600";
                                                                                                                                                                                                                                                                                                                                                                                                                msg.textContent = "Class saved!";

                                                                                                                                                                                                                                                                                                                                                                                                                    form.reset();

                                                                                                                                                                                                                                                                                                                                                                                                                        // Re-render
                                                                                                                                                                                                                                                                                                                                                                                                                            renderTimetable();
                                                                                                                                                                                                                                                                                                                                                                                                                              });

                                                                                                                                                                                                                                                                                                                                                                                                                                // Clear all (DEV/testing convenience)
                                                                                                                                                                                                                                                                                                                                                                                                                                  clearBtn.addEventListener("click", () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                      if (!confirm("Clear all timetable data from this device?")) return;
                                                                                                                                                                                                                                                                                                                                                                                                                                          const empty = { monday: [], tuesday: [], wednesday: [], thursday: [], friday: [] };
                                                                                                                                                                                                                                                                                                                                                                                                                                              saveTimetable(empty);
                                                                                                                                                                                                                                                                                                                                                                                                                                                  renderTimetable();
                                                                                                                                                                                                                                                                                                                                                                                                                                                      document.getElementById("form-msg").textContent = "All cleared.";
                                                                                                                                                                                                                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                                                                                                                                                                                                                        });